# Pandas - Cleansing Data

# 1. 결측치

In [19]:
import pandas as pd

df = pd.read_csv('data/dirtydata.csv', encoding="utf-8") ## 22 행 Date / 8, 28행 Calories

df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [5]:
import pandas as pd

df = pd.read_csv('data/dirtydata.csv')

df.dropna(inplace = True) # inplace = True, DataFrame 원본 변경


df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [7]:
import pandas as pd

df = pd.read_csv('data/dirtydata.csv')

df.fillna(130, inplace = True)

df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     130.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           130    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     130.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [8]:
import pandas as pd

df = pd.read_csv('data/dirtydata.csv')

df["Calories"].fillna(130, inplace = True) # 28번행

df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     130.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     130.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [12]:
import pandas as pd

df = pd.read_csv('data/dirtydata.csv')

x = df["Calories"].mean() # 평균값

print(x)

df["Calories"].fillna(x, inplace = True)

df

304.68

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45           NaN    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60      20201226    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [13]:
import pandas as pd

df = pd.read_csv('data/dirtydata.csv')

x = df["Calories"].median() # 중위값

print(x)

df["Calories"].fillna(x, inplace = True)
df

291.2

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     291.2
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     291.2
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [17]:
import pandas as pd

df = pd.read_csv('data/dirtydata.csv')

x = df["Calories"].mode()[0] # 최빈값

print(x)

df["Calories"].fillna(x, inplace = True)

df

300.0

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     300.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

# 2. 이상치

In [30]:
import pandas as pd
 
df = pd.read_csv('data/dirtydata.csv', encoding="utf-8") # 26 행 Date 형식 / 7 행 Duration 잘못된 데이터 / 11, 12 행 중복

df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [40]:
import pandas as pd

df = pd.read_csv('data/dirtydata.csv')

df['Date'] = pd.to_datetime(df['Date']) # 26 행 날짜 형식 변경

df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [32]:
df.dropna(subset=['Date'], inplace = True) ## 22번 행 제거

df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [38]:
df.loc[7, 'Duration'] = 45 # 450 -> 45
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [43]:
for x in df.index:
    if df.loc[x, "Duration"] > 120:
        df.loc[x, "Duration"] = 120 # 잘못된 값 변경
        
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        120 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [45]:
for x in df.index:
    if df.loc[x, "Duration"] > 120:
        df.drop(x, inplace = True)  # 잘못된 값 변경
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        120 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [46]:
df.duplicated() # 중복 여부 확인

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [18]:
df.drop_duplicates(inplace = True) # 중복 제거

df

      ident   personal    family  taken person quant  reading
0      dyer    William      Dyer    619   dyer   rad     9.82
1        pb      Frank   Pabodie    619   dyer   sal     0.13
2      lake   Anderson      Lake    622   dyer   rad     7.80
3       roe  Valentina   Roerich    622   dyer   sal     0.09
4  danforth      Frank  Danforth    734     pb   rad     8.41

In [20]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [22]:
pd.get_dummies(df['Duration'])

    30   45   60   450
0     0    0    1    0
1     0    0    1    0
2     0    0    1    0
3     0    1    0    0
4     0    1    0    0
5     0    0    1    0
6     0    0    1    0
7     0    0    0    1
8     1    0    0    0
9     0    0    1    0
10    0    0    1    0
11    0    0    1    0
12    0    0    1    0
13    0    0    1    0
14    0    0    1    0
15    0    0    1    0
16    0    0    1    0
17    0    0    1    0
18    0    1    0    0
19    0    0    1    0
20    0    1    0    0
21    0    0    1    0
22    0    1    0    0
23    0    0    1    0
24    0    1    0    0
25    0    0    1    0
26    0    0    1    0
27    0    0    1    0
28    0    0    1    0
29    0    0    1    0
30    0    0    1    0
31    0    0    1    0

In [37]:
df['MaxP'] = pd.cut(x = df['Maxpulse'], bins=[100, 120, 150], labels=['Low', 'High'])
df

    Duration          Date  Pulse  Maxpulse  Calories  MaxP
0         60  '2020/12/01'    110       130     409.1  High
1         60  '2020/12/02'    117       145     479.0  High
2         60  '2020/12/03'    103       135     340.0  High
3         45  '2020/12/04'    109       175     282.4   NaN
4         45  '2020/12/05'    117       148     406.0  High
5         60  '2020/12/06'    102       127     300.0  High
6         60  '2020/12/07'    110       136     374.0  High
7        450  '2020/12/08'    104       134     253.3  High
8         30  '2020/12/09'    109       133     195.1  High
9         60  '2020/12/10'     98       124     269.0  High
10        60  '2020/12/11'    103       147     329.3  High
11        60  '2020/12/12'    100       120     250.7   Low
12        60  '2020/12/12'    100       120     250.7   Low
13        60  '2020/12/13'    106       128     345.3  High
14        60  '2020/12/14'    104       132     379.3  High
15        60  '2020/12/15'     98       123     275.0  High
16        60  '2020/12/16'     98       120     215.2   Low
17        60  '2020/12/17'    100       120     300.0   Low
18        45  '2020/12/18'     90       112       NaN   Low
19        60  '2020/12/19'    103       123     323.0  High
20        45  '2020/12/20'     97       125     243.0  High
21        60  '2020/12/21'    108       131     364.2  High
22        45           NaN    100       119     282.0   Low
23        60  '2020/12/23'    130       101     300.0   Low
24        45  '2020/12/24'    105       132     246.0  High
25        60  '2020/12/25'    102       126     334.5  High
26        60      20201226    100       120     250.0   Low
27        60  '2020/12/27'     92       118     241.0   Low
28        60  '2020/12/28'    103       132       NaN  High
29        60  '2020/12/29'    100       132     280.0  High
30        60  '2020/12/30'    102       129     380.3  High
31        60  '2020/12/31'     92       115     243.0   Low

In [38]:
bins = [df['Maxpulse'].min(), 120, df['Maxpulse'].max()]

df['MaxP'] = pd.cut(x = df['Maxpulse'], bins=bins, labels=['Low', 'High'])
df

    Duration          Date  Pulse  Maxpulse  Calories  MaxP
0         60  '2020/12/01'    110       130     409.1  High
1         60  '2020/12/02'    117       145     479.0  High
2         60  '2020/12/03'    103       135     340.0  High
3         45  '2020/12/04'    109       175     282.4  High
4         45  '2020/12/05'    117       148     406.0  High
5         60  '2020/12/06'    102       127     300.0  High
6         60  '2020/12/07'    110       136     374.0  High
7        450  '2020/12/08'    104       134     253.3  High
8         30  '2020/12/09'    109       133     195.1  High
9         60  '2020/12/10'     98       124     269.0  High
10        60  '2020/12/11'    103       147     329.3  High
11        60  '2020/12/12'    100       120     250.7   Low
12        60  '2020/12/12'    100       120     250.7   Low
13        60  '2020/12/13'    106       128     345.3  High
14        60  '2020/12/14'    104       132     379.3  High
15        60  '2020/12/15'     98       123     275.0  High
16        60  '2020/12/16'     98       120     215.2   Low
17        60  '2020/12/17'    100       120     300.0   Low
18        45  '2020/12/18'     90       112       NaN   Low
19        60  '2020/12/19'    103       123     323.0  High
20        45  '2020/12/20'     97       125     243.0  High
21        60  '2020/12/21'    108       131     364.2  High
22        45           NaN    100       119     282.0   Low
23        60  '2020/12/23'    130       101     300.0   NaN
24        45  '2020/12/24'    105       132     246.0  High
25        60  '2020/12/25'    102       126     334.5  High
26        60      20201226    100       120     250.0   Low
27        60  '2020/12/27'     92       118     241.0   Low
28        60  '2020/12/28'    103       132       NaN  High
29        60  '2020/12/29'    100       132     280.0  High
30        60  '2020/12/30'    102       129     380.3  High
31        60  '2020/12/31'     92       115     243.0   Low

In [44]:
df_new=df.loc[1:30]

df.groupby()

    Duration          Date  Pulse  Maxpulse  Calories  MaxP
1         60  '2020/12/02'    117       145     479.0  High
2         60  '2020/12/03'    103       135     340.0  High
3         45  '2020/12/04'    109       175     282.4  High
4         45  '2020/12/05'    117       148     406.0  High
5         60  '2020/12/06'    102       127     300.0  High
6         60  '2020/12/07'    110       136     374.0  High
7        450  '2020/12/08'    104       134     253.3  High
8         30  '2020/12/09'    109       133     195.1  High
9         60  '2020/12/10'     98       124     269.0  High
10        60  '2020/12/11'    103       147     329.3  High
11        60  '2020/12/12'    100       120     250.7   Low
12        60  '2020/12/12'    100       120     250.7   Low
13        60  '2020/12/13'    106       128     345.3  High
14        60  '2020/12/14'    104       132     379.3  High
15        60  '2020/12/15'     98       123     275.0  High
16        60  '2020/12/16'     98       120     215.2   Low
17        60  '2020/12/17'    100       120     300.0   Low
18        45  '2020/12/18'     90       112       NaN   Low
19        60  '2020/12/19'    103       123     323.0  High
20        45  '2020/12/20'     97       125     243.0  High
21        60  '2020/12/21'    108       131     364.2  High
22        45           NaN    100       119     282.0   Low
23        60  '2020/12/23'    130       101     300.0   NaN
24        45  '2020/12/24'    105       132     246.0  High
25        60  '2020/12/25'    102       126     334.5  High
26        60      20201226    100       120     250.0   Low
27        60  '2020/12/27'     92       118     241.0   Low
28        60  '2020/12/28'    103       132       NaN  High
29        60  '2020/12/29'    100       132     280.0  High
30        60  '2020/12/30'    102       129     380.3  High

In [51]:
df = df.sort_values('Duration')
df = df.reset_index()
df

    index  Duration          Date  Pulse  Maxpulse  Calories  MaxP
0       8        30  '2020/12/09'    109       133     195.1  High
1      18        45  '2020/12/18'     90       112       NaN   Low
2       3        45  '2020/12/04'    109       175     282.4  High
3       4        45  '2020/12/05'    117       148     406.0  High
4      20        45  '2020/12/20'     97       125     243.0  High
5      24        45  '2020/12/24'    105       132     246.0  High
6      22        45           NaN    100       119     282.0   Low
7      28        60  '2020/12/28'    103       132       NaN  High
8       0        60  '2020/12/01'    110       130     409.1  High
9      30        60  '2020/12/30'    102       129     380.3  High
10     14        60  '2020/12/14'    104       132     379.3  High
11      2        60  '2020/12/03'    103       135     340.0  High
12      6        60  '2020/12/07'    110       136     374.0  High
13     13        60  '2020/12/13'    106       128     345.3  High
14     21        60  '2020/12/21'    108       131     364.2  High
15     25        60  '2020/12/25'    102       126     334.5  High
16     10        60  '2020/12/11'    103       147     329.3  High
17     19        60  '2020/12/19'    103       123     323.0  High
18     23        60  '2020/12/23'    130       101     300.0   NaN
19     17        60  '2020/12/17'    100       120     300.0   Low
20     26        60      20201226    100       120     250.0   Low
21      5        60  '2020/12/06'    102       127     300.0  High
22     29        60  '2020/12/29'    100       132     280.0  High
23     27        60  '2020/12/27'     92       118     241.0   Low
24     31        60  '2020/12/31'     92       115     243.0   Low
25     16        60  '2020/12/16'     98       120     215.2   Low
26     11        60  '2020/12/12'    100       120     250.7   Low
27     12        60  '2020/12/12'    100       120     250.7   Low
28      9        60  '2020/12/10'     98       124     269.0  High
29     15        60  '2020/12/15'     98       123     275.0  High
30      1        60  '2020/12/02'    117       145     479.0  High
31      7       450  '2020/12/08'    104       134     253.3  High